keys:
  - &minipc age1k9kqxkxytqxhpcfhhqfkq0p4p8m6lschurs862jzj6futfqukpqsepaep9
  - &mustafa age1lfhm9yth5recdtjrndrf266t3e5ejhprmdn9ssf7nhcxy4d77cjq3px0a6

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *minipc
          - *mustafa
